# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.validate:
        class: AppBundle\Service\Validate
        arguments: ['@validator']
